### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by xbw12138** [atuljha23/Anomaly-Detection-Using-ARIMA#1]
Dataset: S5 - A Labeled Anomaly Detection Dataset

Download dataset need edu email.
Can you provide this dataset

**Comment by atuljha23** [comment]
mail me here jhaat@tcd.ie

**Comment by rekyyang** [comment]
Can you provide this dataset to me? Because I can't register Yahoo mail by China Mainland phone number. thanks
my email is 511965710@qq.com

**Comment by atuljha23** [comment]
Sent to your email address.

**Comment by lipei-hust** [comment]
hello! I'm sorry to disturb you. I have an anomaly detection experiment to test on this dataset. Can you provide me with this dataset? My email address is:451018506@qq.com

**Comment by mengdong1037** [comment]
hi! Would you please provide this dataset to me? 
My email is 805394333@qq.com

**Comment by hlwang200009** [comment]
Hello! I also have an anomaly detection experiment to test on this dataset. Can you mail me : hlwang200009@gmail.com.

**Comment by Xander-cloudwise** [comment]
Hello! Sorry to bother you. I have an anomaly detection experiment on Yahoo S5 dataset. Can you mail me : xinjun_xu@163.com.

**Comment by enzolona** [comment]
Hello! Sorry to bother you. I'm trying to do an Anomaly detection simulation on the Yahoo Webscope s5 Dataset but it seems that the yahoo website might have some problems lately. Would you kindly mail it to me? My email adress is lonardoni.enzo@gmail.com
